stages:
  - test_cpp


T:x86_64-linux:
  image: registry.sensetime.com/kestrel/kestrel_ci:1.4-ubuntu18.04-amd64-gcc75
  stage: test_cpp
  script:
    - export HTTPS_PROXY=http://172.16.1.135:3128 # for github clone
    - cmake -S. -Bbuild -DENABLE_TEST=ON
    - cmake --build build -j4
    - cd build
    - wget -q http://10.4.11.59:18080/resources/XRlab/xrprimer.tar.gz && tar -xzf xrprimer.tar.gz && rm xrprimer.tar.gz
    - ln -sfn xrprimer/test test
    - ./bin/ut_test
