name: deploy

on:
  push:
    branches:
      - 'deploy*'
    tags:
      - 'v*'

jobs:
  build-n-publish:
    runs-on: ubuntu-22.04
    container:
      image: openxrlab/xrprimer_ci:manylinux2014_x86_64_torch1110_mmcv170
    steps:
      - uses: actions/checkout@v2
      - name: Build XRPrimer
        run: |
          source /opt/miniconda/etc/profile.d/conda.sh && conda activate py-${{ matrix.python-version }}
          conan remote add openxrlab http://conan.openxrlab.org.cn/artifactory/api/conan/openxrlab
          for i in 6 7 8 9 10; do \
            conda activate "py-3.$i" && \
            python setup.py bdist_wheel && \
            conda deactivate; \
          done
      - name: Publish distribution to PyPI
        run: |
          source /opt/miniconda/etc/profile.d/conda.sh && conda activate py-${{ matrix.python-version }}
          for i in $( ls dist/*-linux_x86_64.whl ); do auditwheel repair $i; done
          for i in $( ls dist/*-linux_x86_64.whl ); do mv $i ${i%-linux*}-manylinux2014_x86_64.whl; done
          du -sh wheelhouse/*
          for i in $( ls wheelhouse/*.whl ); do auditwheel show $i; done
          twine upload wheelhouse/* -u __token__ -p ${{ secrets.PYPI_PASSWORD }}
